theme: jekyll-theme-leap-day
title: SRU Schnittstelle zum Online-Archivkatalog des Stadtarchivs Zürich
description: Eine Anleitung zum Umgang mit der SRU Schnittstelle zum Online-Archivkatalog des Stadtarchivs Zürich
show_downloads: false
